# Generated by Django 4.0.5 on 2022-06-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='NOMBRE!!')),
                ('apellido', models.CharField(max_length=20, verbose_name='APELLIDO!!')),
                ('nacimiento', models.DateTimeField(verbose_name='NACIMIENTO!!')),
                ('edad', models.IntegerField(verbose_name='EDAD!!')),
                ('email', models.EmailField(max_length=254, verbose_name='EMAIL!!')),
            ],
        ),
    ]
